###
@eventId = {{ createEvent.response.body.id }}

###
@spotId = {{ createSpot.response.body.id }}

###
@spotName = {{ createSpot.response.body.name }}

###
GET http://localhost:3000/events

###
GET http://localhost:3000/events/{{eventId}}

###
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
  "name": "Event 1",
  "date": "2019-01-01",
  "description": "Description 1",
  "price": 100
}

###
PATCH http://localhost:3000/events/{{eventId}}
Content-Type: application/json

{
  "name": "Updated Event",
  "date": "2019-01-01",
  "description": "Updated Description",
  "price": 100
}

###
DELETE http://localhost:3000/events/{{eventId}}


###
GET http://localhost:3000/events/{{eventId}}/spots

###
GET http://localhost:3000/events/{{eventId}}/spots/{{spotId}}

###
# @name createSpot
POST http://localhost:3000/events/{{eventId}}/spots
Content-Type: application/json

{
  "name": "A1"
}

###
PATCH http://localhost:3000/events/{{eventId}}/spots/{{spotId}}
Content-Type: application/json

{
  "name": "A2"
}

###
DELETE http://localhost:3000/events/{{eventId}}/spots/{{spotId}}

###
POST http://localhost:3000/events/{{eventId}}/reserve
Content-Type: application/json

{
  "spots": ["{{ spotName }}"],
  "ticket_kind" : "full",
  "email": "test@teste.com"
}